### PR TITLE
Module federation approach

### PR DESCRIPTION
**Pull request by honohunter**

### CODE REVIEW

**Comment by ScriptedAlchemy** [comment]
Any reason this didn’t work out? Perhaps i can help resolve if module federation is still useful

**Comment by honohunter** [comment]
@ScriptedAlchemy Thank you for your reply,
module federation worked fine after some tweaks and its really a great concept for microfrontends revolution, The reason why we dropped this approach because we decided to wait until it became mature enough to switch over.

**Comment by ScriptedAlchemy** [comment]
Ahh okay. No worries. Beta 17 is going to be pretty solid. But we may change a key in the config during beta 18. I’ll confirm this with the working group and see if we plan on any big breaking changes. You’ll at least be able to weigh the benefits of waiting or using haha

**Comment by honohunter** [comment]
I'm looking forward to this

**Pull request closed without merging**
